<?php
require_once __DIR__ . '/../vendor/autoload.php';
require 'db.php';

use Mpdf\Mpdf;
use Google\Client;
use Google\Service\Drive;

// 🔥 Get IMEI
$imei = $_GET['imei'] ?? die("IMEI not provided");

// 🔥 Fetch Data
$sql = "SELECT * FROM purchased_mobiles WHERE IMEI = '$imei'";
$result = mysqli_query($conn, $sql);
if (!$result || mysqli_num_rows($result) == 0) {
    die("IMEI not found.");
}
$row = mysqli_fetch_assoc($result);

// ✅ Initialize Mpdf
$mpdf = new Mpdf([
    'format' => 'A4',
    'margin_top' => 50,
    'margin_bottom' => 20,
    'margin_header' => 10,
    'margin_footer' => 10,
]);

// ✅ Watermark
$mpdf->SetWatermarkText('SmartMobileApp');
$mpdf->showWatermarkText = true;
$mpdf->watermarkTextAlpha = 0.05;

// ✅ Header
$mpdf->SetHTMLHeader('
<div style="background-color:#fff; border-bottom:2px solid #5409DA; padding: 10px 0;">
    <div style="display: flex; align-items:center;">
        <div style="flex:1;">
            <img src="../assets/logo.png" height="70">
        </div>
        <div style="flex:3; text-align:right;">
            <div style="font-size:22px; font-weight: bold; color:#5409DA;">SmartMobileApp</div>
            <div style="font-size:14px; color:#4E71FF;">Return Invoice</div>
            <div style="font-size:12px; color:#333;">Date: ' . date("d-m-Y") . '</div>
            <div style="font-size:12px; color:#333;">IMEI: ' . $imei . '</div>
        </div>
    </div>
</div>
');

// ✅ Footer
$mpdf->SetHTMLFooter('
    <div style="text-align:center; font-size:10px; color:#4E71FF;">
        Thank you for using SmartMobileApp | Page {PAGENO}
    </div>
');

// ✅ Stylesheet
$stylesheet = '
body {font-family: sans-serif; color: #222;}
.heading {
    color: #5409DA;
    font-size: 20px;
    font-weight: bold;
    margin-bottom: 12px;
}
table {
    border-collapse: collapse;
    width: 100%;
}
th, td {
    border: 1px solid #5409DA;
    padding: 10px;
    font-size: 12px;
}
th {
    background-color: #5409DA;
    color: white;
    font-weight: bold;
    font-size: 13px;
}
td:last-child {
    text-align: right;
}
tr:nth-child(even) {
    background-color: #f9f9f9;
}
.footer-note {
    margin-top: 20px;
    color: #4E71FF;
    font-style: italic;
    font-size: 11px;
}
';

// ✅ HTML Content
$html = '
<div class="heading">▸ Return Details</div>

<table>
    <tr><th>IMEI</th><td>' . htmlspecialchars($row['IMEI']) . '</td></tr>
    <tr><th>Mobile Name</th><td>' . htmlspecialchars($row['mobile_name']) . '</td></tr>
    <tr><th>Buyer Name</th><td>' . htmlspecialchars($row['buyer_name']) . '</td></tr>
    <tr><th>Buyer Mobile</th><td>' . htmlspecialchars($row['buyer_mobile']) . '</td></tr>
    <tr><th>Return Description</th><td>' . htmlspecialchars($row['return_description']) . '</td></tr>
    <tr><th>Return Date</th><td>' . htmlspecialchars($row['return_date']) . '</td></tr>
</table>

<p class="footer-note">This document is auto-generated by SmartMobileApp. Thank you!</p>
';

// ✅ Write to PDF
$mpdf->WriteHTML($stylesheet, \Mpdf\HTMLParserMode::HEADER_CSS);
$mpdf->WriteHTML($html);

// ✅ Save PDF Locally
$pdfFileName = "Return_" . $imei . ".pdf";
$pdfFilePath = __DIR__ . "/temp/" . $pdfFileName;
if (!file_exists(__DIR__ . "/temp")) {
    mkdir(__DIR__ . "/temp", 0777, true);
}
$mpdf->Output($pdfFilePath, 'F');

// ✅ Upload to Google Drive
$client = new Client();
$client->setAuthConfig('credentials.json');
$client->addScope(Drive::DRIVE);
$service = new Drive($client);

// 🔥 Fetch Folder ID
$folderSql = "SELECT drive_folder_id FROM purchased_mobiles WHERE IMEI = '$imei'";
$folderResult = mysqli_query($conn, $folderSql);
if (!$folderResult || mysqli_num_rows($folderResult) == 0) {
    die("❌ Drive folder not found.");
}
$folderRow = mysqli_fetch_assoc($folderResult);
$folderId = $folderRow['drive_folder_id'];

// 🔥 Upload File
$fileMetadata = new Drive\DriveFile([
    'name' => $pdfFileName,
    'parents' => [$folderId]
]);

$content = file_get_contents($pdfFilePath);

$file = $service->files->create($fileMetadata, [
    'data' => $content,
    'mimeType' => 'application/pdf',
    'uploadType' => 'multipart',
    'fields' => 'id'
]);

// 🔥 Set Permission
$permission = new Drive\Permission([
    'type' => 'anyone',
    'role' => 'reader'
]);
$service->permissions->create($file->id, $permission);

$pdfLink = "https://drive.google.com/file/d/" . $file->id . "/view";

// 🔥 Delete Temp PDF
unlink($pdfFilePath);

mysqli_close($conn);

// ✅ Redirect to Success
header("Location: ../success.php?imei=$imei&pdf=" . urlencode($pdfLink));
exit;
?>
