<?php
require_once __DIR__ . '/../vendor/autoload.php';
require 'db.php';

use Mpdf\Mpdf;
use Google\Client;
use Google\Service\Drive;

// 🔥 Parent Drive Folder (IMEI folders are inside this)
$parentFolderId = '1Ah8EfWG-SpHPxZlggOk8VCCqfY_Q73W5';

// 🔥 Get IMEI
$imei = $_GET['imei'] ?? die("IMEI not provided");

// 🔥 Fetch Data from Database
$sql = "SELECT * FROM purchased_mobiles WHERE IMEI = '$imei'";
$result = mysqli_query($conn, $sql);
if (!$result || mysqli_num_rows($result) == 0) {
    die("IMEI not found.");
}
$row = mysqli_fetch_assoc($result);

// 🔥 Initialize Google Client
$client = new Client();
$client->setAuthConfig('credentials.json');
$client->addScope(Drive::DRIVE);
$service = new Drive($client);

// 🔥 Find IMEI Folder in Google Drive
$imeiFolderQuery = "mimeType = 'application/vnd.google-apps.folder' 
    and name = '$imei' 
    and '$parentFolderId' in parents";

$imeiFolders = $service->files->listFiles([
    'q' => $imeiFolderQuery,
    'fields' => 'files(id, name)'
]);

if (count($imeiFolders->getFiles()) == 0) {
    die("❌ IMEI folder not found on Google Drive.");
}
$imeiFolderId = $imeiFolders->getFiles()[0]->getId();

// 🔥 Find All Image Files in IMEI Folder
$imageQuery = "'$imeiFolderId' in parents and (mimeType contains 'image/')";
$imageFiles = $service->files->listFiles([
    'q' => $imageQuery,
    'fields' => 'files(id, name, mimeType)'
]);

// 🔥 Download Image Function
function downloadDriveFile($service, $fileId) {
    $response = $service->files->get($fileId, ['alt' => 'media']);
    $content = $response->getBody()->getContents();

    $tmpFile = tempnam(sys_get_temp_dir(), 'img_');
    file_put_contents($tmpFile, $content);

    return $tmpFile;
}

// 🔥 Initialize Mpdf
$mpdf = new Mpdf([
    'format' => 'A4',
    'margin_top' => 50,
    'margin_bottom' => 20,
    'margin_header' => 10,
    'margin_footer' => 10,
]);

// ✅ Watermark
$mpdf->SetWatermarkText('SmartMobileApp');
$mpdf->showWatermarkText = true;
$mpdf->watermarkTextAlpha = 0.05;

// ✅ Header
$mpdf->SetHTMLHeader('
<div style="background-color:#fff; border-bottom:2px solid #5409DA; padding: 10px 0;">
    <div style="display: flex; align-items:center;">
        <div style="flex:1;">
            <img src="../assets/logo.png" height="80">
        </div>
        <div style="flex:3; text-align:right;">
            <div style="font-size:22px; font-weight: bold; color:#5409DA;">SmartMobileApp</div>
            <div style="font-size:14px; color:#4E71FF;">Purchase Invoice</div>
            <div style="font-size:12px; color:#333;">Date: '.date("d-m-Y").'</div>
            <div style="font-size:12px; color:#333;">IMEI: '.$imei.'</div>
        </div>
    </div>
</div>
');

// ✅ Footer
$mpdf->SetHTMLFooter('
    <div style="text-align:center; font-size:10px; color:#4E71FF;">
        Thank you for using SmartMobileApp | Page {PAGENO}
    </div>
');

// ✅ Styles
$stylesheet = '
body {font-family: sans-serif; color: #222;}
h2 {color: #5409DA; margin-bottom: 10px;}
table {border-collapse: collapse; width: 100%;}
th, td {border: 1px solid #5409DA; padding: 10px; font-size: 12px;}
th {background-color: #5409DA; color: white; font-weight: bold; font-size: 13px;}
td:last-child {text-align: right;}
tr:nth-child(even) {background-color: #f9f9f9;}
.footer-note {margin-top: 20px; color: #4E71FF; font-style: italic; font-size: 11px;}
.image-grid {display: flex; flex-wrap: wrap; gap: 10px; margin-top: 10px;}
.image-grid img {width: 150px; border: 2px solid #5409DA; border-radius: 8px;}
';

// ✅ PDF Content
$html = '
<h2>Purchase Details</h2>
<table>
    <tr><th>IMEI</th><td>' . htmlspecialchars($row['IMEI']) . '</td></tr>
    <tr><th>Mobile Name</th><td>' . htmlspecialchars($row['mobile_name']) . '</td></tr>
    <tr><th>Seller Name</th><td>' . htmlspecialchars($row['seller_name']) . '</td></tr>
    <tr><th>Seller Mobile</th><td>' . htmlspecialchars($row['seller_mobile']) . '</td></tr>
    <tr><th>Fault Description</th><td>' . htmlspecialchars($row['fault_description']) . '</td></tr>
    <tr><th>Purchased Price</th><td>₹ ' . htmlspecialchars($row['purchase_price']) . '</td></tr>
    <tr><th>Purchase Date</th><td>' . htmlspecialchars($row['purchase_date']) . '</td></tr>
</table>
';

// ✅ Add Seller Photos if Available
if (count($imageFiles->getFiles()) > 0) {
    $html .= '<h2>Seller Photos</h2><div class="image-grid">';
    foreach ($imageFiles->getFiles() as $file) {
        $localPath = downloadDriveFile($service, $file->getId());
        $base64 = base64_encode(file_get_contents($localPath));
        $mimeType = mime_content_type($localPath);
        unlink($localPath); // Clean temp file

        $html .= '<img src="data:' . $mimeType . ';base64,' . $base64 . '">';
    }
    $html .= '</div>';
}

// ✅ Footer Note
$html .= '<p class="footer-note">This document is auto-generated by SmartMobileApp. Thank you!</p>';

// ✅ Write to PDF
$mpdf->WriteHTML($stylesheet, \Mpdf\HTMLParserMode::HEADER_CSS);
$mpdf->WriteHTML($html);

// ✅ Save PDF Locally
$pdfFileName = $imei . ".pdf";
$pdfFilePath = __DIR__ . "/temp/" . $pdfFileName;
if (!file_exists(__DIR__ . "/temp")) {
    mkdir(__DIR__ . "/temp", 0777, true);
}
$mpdf->Output($pdfFilePath, 'F');

// ✅ Upload PDF to Google Drive
$fileMetadata = new Drive\DriveFile([
    'name' => $pdfFileName,
    'parents' => [$imeiFolderId]
]);

$content = file_get_contents($pdfFilePath);

$file = $service->files->create($fileMetadata, [
    'data' => $content,
    'mimeType' => 'application/pdf',
    'uploadType' => 'multipart',
    'fields' => 'id'
]);

// ✅ Set Permission
$permission = new Drive\Permission([
    'type' => 'anyone',
    'role' => 'reader'
]);
$service->permissions->create($file->id, $permission);

$pdfLink = "https://drive.google.com/file/d/" . $file->id . "/view";

// ✅ Delete Temp PDF
unlink($pdfFilePath);

mysqli_close($conn);

// ✅ Redirect to Success Page
header("Location: ../success.php?imei=$imei&pdf=" . urlencode($pdfLink));
exit;
?>
