<?php
require_once __DIR__ . '/../vendor/autoload.php';
require 'db.php';

use Mpdf\Mpdf;
use Google\Client;
use Google\Service\Drive;

$imei = $_GET['imei'] ?? die("IMEI not provided");

// 🔍 Fetch data from DB
$sql = "SELECT * FROM purchased_mobiles WHERE IMEI = '$imei'";
$result = mysqli_query($conn, $sql);
if (!$result || mysqli_num_rows($result) == 0) {
    die("IMEI not found.");
}
$row = mysqli_fetch_assoc($result);
$imeiFolderId = $row['drive_folder_id'];

// 🔐 Google Client
$client = new Client();
$client->setAuthConfig('credentials.json');
$client->addScope(Drive::DRIVE);
$service = new Drive($client);

// 🧠 Helper
function downloadDriveImage($service, $fileId) {
    $response = $service->files->get($fileId, ['alt' => 'media']);
    $content = $response->getBody()->getContents();
    $tmp = tempnam(sys_get_temp_dir(), 'img_');
    file_put_contents($tmp, $content);
    return $tmp;
}

// ✅ Init mPDF
$mpdf = new Mpdf([
    'format' => 'A4',
    'margin_top' => 50,
    'margin_bottom' => 20,
    'margin_header' => 10,
    'margin_footer' => 10,
]);

$mpdf->SetWatermarkText('SmartMobileApp');
$mpdf->showWatermarkText = true;
$mpdf->watermarkTextAlpha = 0.05;

// ✅ Header & Footer
$mpdf->SetHTMLHeader('
<div style="background-color:#fff; border-bottom:2px solid #5409DA; padding: 10px 0;">
    <div style="display: flex; align-items:center;">
        <div style="flex:1;"><img src="../assets/logo.png" height="60"></div>
        <div style="flex:3; text-align:right;">
            <div style="font-size:22px; font-weight: bold; color:#5409DA;">SmartMobileApp</div>
            <div style="font-size:14px; color:#4E71FF;">Sale Invoice</div>
            <div style="font-size:12px;">IMEI: ' . $imei . '</div>
            <div style="font-size:12px;">Date: ' . date("d-m-Y") . '</div>
        </div>
    </div>
</div>
');

$mpdf->SetHTMLFooter('
<div style="text-align:center; font-size:10px; color:#4E71FF;">
    Generated by SmartMobileApp | Page {PAGENO}
</div>');

// ✅ CSS
$style = '
body { font-family: sans-serif; color: #222; }
h1, h2 { color: #5409DA; margin-top: 20px; }
table { border-collapse: collapse; width: 100%; margin-bottom: 15px; }
th, td { border: 1px solid #5409DA; padding: 8px; font-size: 12px; }
th { background-color: #5409DA; color: white; font-weight: bold; }
.image-grid { display: flex; flex-wrap: wrap; gap: 10px; margin: 10px 0 20px 0; }
.image-grid img { width: 120px; border: 2px solid #5409DA; border-radius: 8px; }
.footer-note { font-style: italic; font-size: 11px; color: #4E71FF; }
';

$html = '<h1>Mobile Sale Summary</h1>';

$html .= '<h2>Product Information</h2><table>';
$html .= '<tr><th>IMEI</th><td>' . htmlspecialchars($row['IMEI']) . '</td></tr>';
$html .= '<tr><th>Mobile Name</th><td>' . htmlspecialchars($row['mobile_name']) . '</td></tr>';
$html .= '</table>';

$html .= '<h2>Seller Details</h2><table>';
$html .= '<tr><th>Name</th><td>' . htmlspecialchars($row['seller_name']) . '</td></tr>';
$html .= '<tr><th>Mobile</th><td>' . htmlspecialchars($row['seller_mobile']) . '</td></tr>';
$html .= '<tr><th>Purchase Price</th><td>₹ ' . htmlspecialchars($row['purchase_price']) . '</td></tr>';
$html .= '<tr><th>Purchase Date</th><td>' . date("d-m-Y", strtotime($row['purchase_date'])) . '</td></tr>';
$html .= '</table>';

$html .= '<div class="image-grid">';
$sellerPhotos = json_decode($row['seller_photo'], true) ?? [];
foreach ($sellerPhotos as $url) {
    if (preg_match('/\/d\/(.*?)\//', $url, $m)) {
        $img = downloadDriveImage($service, $m[1]);
        $b64 = base64_encode(file_get_contents($img));
        $mime = mime_content_type($img);
        unlink($img);
        $html .= '<img src="data:' . $mime . ';base64,' . $b64 . '">';
    }
}
$html .= '</div>';

$html .= '<h2>Buyer Details</h2><table>';
$html .= '<tr><th>Name</th><td>' . htmlspecialchars($row['buyer_name']) . '</td></tr>';
$html .= '<tr><th>Mobile</th><td>' . htmlspecialchars($row['buyer_mobile']) . '</td></tr>';
$html .= '<tr><th>Sold Price</th><td>₹ ' . htmlspecialchars($row['sold_price']) . '</td></tr>';
$html .= '<tr><th>Sold Date</th><td>' . date("d-m-Y", strtotime($row['sell_date'])) . '</td></tr>';
$html .= '</table>';

$html .= '<div class="image-grid">';
$buyerPhotos = json_decode($row['buyer_photo'], true) ?? [];
foreach ($buyerPhotos as $url) {
    if (preg_match('/\/d\/(.*?)\//', $url, $m)) {
        $img = downloadDriveImage($service, $m[1]);
        $b64 = base64_encode(file_get_contents($img));
        $mime = mime_content_type($img);
        unlink($img);
        $html .= '<img src="data:' . $mime . ';base64,' . $b64 . '">';
    }
}
$html .= '</div>';

$html .= '<h2>Verification Videos</h2><table>';
$html .= '<tr><th>Buyer Verification</th><td><a href="' . htmlspecialchars($row['buyer_verification']) . '" target="_blank">View Video</a></td></tr>';
$html .= '<tr><th>Seller Verification</th><td><a href="' . htmlspecialchars($row['seller_verification_video']) . '" target="_blank">View Video</a></td></tr>';
$html .= '</table>';

// ✅ Optional: Return Section (only if returned)
if (!empty($row['return_description'])) {
    $html .= '<h2>Return Details</h2><table>';
    $html .= '<tr><th>Return Description</th><td>' . htmlspecialchars($row['return_description']) . '</td></tr>';
    $html .= '<tr><th>Return Date</th><td>' . date("d-m-Y", strtotime($row['return_date'])) . '</td></tr>';
    $html .= '<tr><th>Return Verification</th><td><a href="' . htmlspecialchars($row['return_verification']) . '" target="_blank">View Video</a></td></tr>';
    $html .= '</table>';

    $html .= '<div class="image-grid">';
    $returnPhotos = json_decode($row['return_photo'], true) ?? [];
    foreach ($returnPhotos as $url) {
        if (preg_match('/\/d\/(.*?)\//', $url, $m)) {
            $img = downloadDriveImage($service, $m[1]);
            $b64 = base64_encode(file_get_contents($img));
            $mime = mime_content_type($img);
            unlink($img);
            $html .= '<img src="data:' . $mime . ';base64,' . $b64 . '">';
        }
    }
    $html .= '</div>';
}

$html .= '<p class="footer-note">This document is auto-generated by SmartMobileApp. Thank you!</p>';

// ✅ Save PDF locally
$pdfName = "Mobile_Sale_" . $imei . ".pdf";
$pdfPath = __DIR__ . '/../temp/' . $pdfName;
if (!file_exists(dirname($pdfPath))) mkdir(dirname($pdfPath), 0777, true);

$mpdf->WriteHTML($style, \Mpdf\HTMLParserMode::HEADER_CSS);
$mpdf->WriteHTML($html);
$mpdf->Output($pdfPath, 'F');

// ✅ Upload/Replace in Google Drive
$existingFile = $service->files->listFiles([
    'q' => "'$imeiFolderId' in parents and name = '$pdfName'",
    'fields' => 'files(id, name)',
]);

$pdfContent = file_get_contents($pdfPath);
if (count($existingFile->getFiles()) > 0) {
    $fileId = $existingFile->getFiles()[0]->getId();
    $service->files->update($fileId, new Drive\DriveFile(), [
        'data' => $pdfContent,
        'mimeType' => 'application/pdf',
        'uploadType' => 'media',
    ]);
    $uploadedId = $fileId;
} else {
    $newFile = $service->files->create(new Drive\DriveFile([
        'name' => $pdfName,
        'parents' => [$imeiFolderId]
    ]), [
        'data' => $pdfContent,
        'mimeType' => 'application/pdf',
        'uploadType' => 'multipart',
        'fields' => 'id'
    ]);
    $uploadedId = $newFile->id;
}

$service->permissions->create($uploadedId, new Drive\Permission([
    'type' => 'anyone',
    'role' => 'reader'
]));

unlink($pdfPath);
mysqli_close($conn);

header("Location: ../success.php?imei=$imei&pdf=https://drive.google.com/file/d/$uploadedId/view");
exit;
