<?php
require_once __DIR__ . '/../vendor/autoload.php';
require 'db.php';

use Mpdf\Mpdf;
use Google\Client;
use Google\Service\Drive;

// 🔍 Get IMEI
$imei = $_GET['imei'] ?? die("IMEI not provided");

// 🔍 Fetch from database
$sql = "SELECT * FROM purchased_mobiles WHERE IMEI = '$imei'";
$result = mysqli_query($conn, $sql);
if (!$result || mysqli_num_rows($result) === 0) {
    die("IMEI not found in DB.");
}
$row = mysqli_fetch_assoc($result);
$imeiFolderId = $row['drive_folder_id'];

// 🔐 Google Drive Client
$client = new Client();
$client->setAuthConfig('credentials.json');
$client->addScope(Drive::DRIVE);
$service = new Drive($client);

// 🔧 Helpers
function downloadDriveImage($service, $fileId) {
    $response = $service->files->get($fileId, ['alt' => 'media']);
    $content = $response->getBody()->getContents();
    $tmp = tempnam(sys_get_temp_dir(), 'img_');
    file_put_contents($tmp, $content);
    return $tmp;
}

// ✅ mPDF Init
$mpdf = new Mpdf([
    'format' => 'A4',
    'margin_top' => 50,
    'margin_bottom' => 20,
    'margin_header' => 10,
    'margin_footer' => 10,
]);
$mpdf->SetWatermarkText('SmartMobileApp');
$mpdf->showWatermarkText = true;
$mpdf->watermarkTextAlpha = 0.05;

// ✅ Header + Footer
$mpdf->SetHTMLHeader('
<div style="background-color:#fff; border-bottom:2px solid #5409DA; padding: 10px 0;">
    <div style="display: flex; align-items:center;">
        <div style="flex:1;">
            <img src="../assets/logo.png" height="60">
        </div>
        <div style="flex:3; text-align:right;">
            <div style="font-size:22px; font-weight: bold; color:#5409DA;">SmartMobileApp</div>
            <div style="font-size:14px; color:#4E71FF;">Purchase Invoice</div>
            <div style="font-size:12px;">IMEI: ' . $imei . '</div>
            <div style="font-size:12px;">Date: ' . date("d-m-Y") . '</div>
        </div>
    </div>
</div>
');
$mpdf->SetHTMLFooter('
    <div style="text-align:center; font-size:10px; color:#4E71FF;">
        Generated by SmartMobileApp | Page {PAGENO}
    </div>
');

// ✅ CSS Styles
$style = '
body { font-family: sans-serif; color: #222; }
h1, h2 { color: #5409DA; margin-top: 20px; }
table { border-collapse: collapse; width: 100%; margin-bottom: 15px; }
th, td { border: 1px solid #5409DA; padding: 8px; font-size: 12px; }
th { background-color: #5409DA; color: white; font-weight: bold; }
.image-grid { display: flex; flex-wrap: wrap; gap: 10px; margin: 10px 0 20px 0; }
.image-grid img { width: 120px; border: 2px solid #5409DA; border-radius: 8px; }
.footer-note { font-style: italic; font-size: 11px; color: #4E71FF; }
';

// ✅ HTML Content
$html = '<h1>Mobile Purchase Summary</h1>';

$html .= '<h2>Product Information</h2>
<table>
<tr><th>IMEI</th><td>' . htmlspecialchars($row['IMEI']) . '</td></tr>
<tr><th>Mobile Name</th><td>' . htmlspecialchars($row['mobile_name']) . '</td></tr>
</table>';

$html .= '<h2>Seller Details</h2>
<table>
<tr><th>Name</th><td>' . htmlspecialchars($row['seller_name']) . '</td></tr>
<tr><th>Mobile</th><td>' . htmlspecialchars($row['seller_mobile']) . '</td></tr>
<tr><th>Purchase Price</th><td>₹ ' . htmlspecialchars($row['purchase_price']) . '</td></tr>
<tr><th>Purchase Date</th><td>' . date("d-m-Y", strtotime($row['purchase_date'])) . '</td></tr>
</table>';

// ✅ Seller Photos
$html .= '<h2>Seller Photos</h2><div class="image-grid">';
$sellerPhotos = json_decode($row['seller_photo'], true) ?? [];
foreach ($sellerPhotos as $url) {
    if (preg_match('/\/d\/(.*?)\//', $url, $match)) {
        $imgPath = downloadDriveImage($service, $match[1]);
        $b64 = base64_encode(file_get_contents($imgPath));
        $mime = mime_content_type($imgPath);
        unlink($imgPath);
        $html .= '<img src="data:' . $mime . ';base64,' . $b64 . '">';
    }
}
$html .= '</div>';

// ✅ Seller Verification Video
$html .= '<h2>Verification Video</h2>
<table>
<tr><th>Seller Verification</th><td><a href="' . htmlspecialchars($row['seller_verification_video']) . '" target="_blank">View Video</a></td></tr>
</table>';

// ✅ Footer Note
$html .= '<p class="footer-note">This document is auto-generated by SmartMobileApp. Thank you!</p>';

// ✅ Save PDF Locally
$pdfName = "Mobile_Sale_" . $imei . ".pdf";
$pdfPath = __DIR__ . '/../temp/' . $pdfName;
if (!file_exists(dirname($pdfPath))) mkdir(dirname($pdfPath), 0777, true);

$mpdf->WriteHTML($style, \Mpdf\HTMLParserMode::HEADER_CSS);
$mpdf->WriteHTML($html);
$mpdf->Output($pdfPath, 'F');

// ✅ Check if PDF already exists in Drive
$existingFile = $service->files->listFiles([
    'q' => "'$imeiFolderId' in parents and name = '$pdfName'",
    'fields' => 'files(id)',
]);
$pdfContent = file_get_contents($pdfPath);

if (count($existingFile->getFiles()) > 0) {
    // 🔁 Replace existing PDF
    $existingId = $existingFile->getFiles()[0]->getId();
    $updated = $service->files->update($existingId, new Drive\DriveFile(), [
        'data' => $pdfContent,
        'mimeType' => 'application/pdf',
        'uploadType' => 'media',
    ]);
    $uploadedId = $existingId;
} else {
    // ➕ Upload new
    $fileMeta = new Drive\DriveFile([
        'name' => $pdfName,
        'parents' => [$imeiFolderId]
    ]);
    $created = $service->files->create($fileMeta, [
        'data' => $pdfContent,
        'mimeType' => 'application/pdf',
        'uploadType' => 'multipart',
        'fields' => 'id'
    ]);
    $uploadedId = $created->id;
}

// ✅ Make file public
$service->permissions->create($uploadedId, new Drive\Permission([
    'type' => 'anyone',
    'role' => 'reader'
]));

// 🧹 Clean up
unlink($pdfPath);
mysqli_close($conn);

// ✅ Redirect to success
header("Location: ../success.php?imei=$imei&pdf=https://drive.google.com/file/d/$uploadedId/view");
exit;
